import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';

const labels = { autor: 'Autores', categoria: 'Categorias', cliente: 'Clientes', detalle_venta: 'Detalle de ventas', editorial: 'Editoriales', empleado: 'Empleados', libro: 'Libros', libro_autor: 'Libros y autores', metodo_pago: 'Metodos de pago', pago: 'Pagos', rol: 'Roles', rol_usuario: 'Roles de usuario', usuario: 'Usuarios', venta: 'Ventas' };
const primaryKeys = { autor: ['id_autor'], categoria: ['id_categoria'], cliente: ['id_cliente'], detalle_venta: ['id_detalle'], editorial: ['id_editorial'], empleado: ['id_empleado'], libro: ['id_libro'], libro_autor: ['id_libro', 'id_autor'], metodo_pago: ['id_metodo_pago'], pago: ['id_pago'], rol: ['id_rol'], rol_usuario: ['id_rol', 'id_usuario'], usuario: ['id_usuario'], venta: ['id_venta'] };
const relations = { empleado: { id_usuario: 'usuario' }, libro: { id_categoria: 'categoria', id_editorial: 'editorial' }, libro_autor: { id_libro: 'libro', id_autor: 'autor' }, rol_usuario: { id_rol: 'rol', id_usuario: 'usuario' }, venta: { id_cliente: 'cliente', id_empleado: 'empleado' }, detalle_venta: { id_venta: 'venta', id_libro: 'libro' }, pago: { id_venta: 'venta', id_metodo_pago: 'metodo_pago' } };
const API = 'http://localhost:5000/api';
const emptyKeys = [];
const optionText = (row) => row.nombre || row.titulo || row.username || Object.values(row)[0];
const safeRow = ({ password, ...row }) => row;
function storeSnapshot(module, rows) { localStorage.setItem(`venta-libros-${module}`, JSON.stringify(rows.map(safeRow))); }
function storeMovement(action, module, row) { const key = 'venta-libros-historial'; const current = JSON.parse(localStorage.getItem(key) || '[]'); current.unshift({ accion: action, modulo: module, registro: safeRow(row), fecha: new Date().toISOString() }); localStorage.setItem(key, JSON.stringify(current.slice(0, 100))); }

function Modulo() {
  const { modulo } = useParams(); const [data, setData] = useState([]); const [references, setReferences] = useState({}); const [hidden, setHidden] = useState([]); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [editing, setEditing] = useState(null); const [form, setForm] = useState({}); const keys = primaryKeys[modulo] || emptyKeys; const relationMap = relations[modulo] || {};
  const rowId = useCallback((row) => keys.map((key) => String(row[key])).join(':'), [keys]);
  const load = useCallback(async () => { try { setError(''); const response = await fetch(`${API}/${modulo}?limit=100`); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'No fue posible cargar la informacion'); const rows = body[modulo] || []; setData(rows); storeSnapshot(modulo, rows); } catch (requestError) { setError(requestError.message); } }, [modulo]);
  useEffect(() => { setEditing(null); setForm({}); setMessage(''); setHidden(JSON.parse(localStorage.getItem(`venta-libros-ocultos-${modulo}`) || '[]')); load(); }, [modulo, load]);
  const visibleData = useMemo(() => data.filter((row) => !hidden.includes(rowId(row))), [data, hidden, rowId]); const allFields = useMemo(() => data.length ? Object.keys(data[0]) : [], [data]); const displayFields = allFields.filter((field) => field !== 'password'); const formFields = editing ? allFields.filter((field) => !keys.includes(field)) : allFields.filter((field) => keys.length > 1 || !keys.includes(field));
  const openForm = async (row) => { try { const fetched = await Promise.all(Object.entries(relationMap).map(async ([field, table]) => { const response = await fetch(`${API}/${table}?limit=100`); const body = await response.json(); return [field, body[table] || []]; })); setReferences(Object.fromEntries(fetched)); setEditing(row || 'new'); const fields = row ? allFields.filter((field) => !keys.includes(field)) : allFields.filter((field) => keys.length > 1 || !keys.includes(field)); setForm(Object.fromEntries(fields.map((field) => [field, row?.[field] ?? '']))); } catch (requestError) { setError(requestError.message); } };
  const recordPath = (row) => keys.map((key) => encodeURIComponent(row[key])).join('/');
  const save = async (event) => { event.preventDefault(); try { const body = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '')); const isNew = editing === 'new'; const response = await fetch(isNew ? `${API}/${modulo}` : `${API}/${modulo}/${recordPath(editing)}`, { method: isNew ? 'POST' : 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'No fue posible guardar el registro'); storeMovement(isNew ? 'creado' : 'actualizado', modulo, isNew ? { ...body, id: result.id } : { ...editing, ...body }); setMessage(isNew ? 'Registro creado correctamente.' : 'Registro actualizado correctamente.'); setEditing(null); await load(); } catch (requestError) { setError(requestError.message); } };
  const hide = (row) => { const next = [...new Set([...hidden, rowId(row)])]; setHidden(next); localStorage.setItem(`venta-libros-ocultos-${modulo}`, JSON.stringify(next)); storeMovement('ocultado', modulo, row); setMessage('Registro ocultado de esta pagina. No se elimino de MySQL.'); };
  return <section className="data-panel"><Link className="back-link" to="/">Volver al inicio</Link><h1>{labels[modulo] || modulo}</h1><p>{visibleData.length} registros mostrados</p><button type="button" onClick={() => openForm(null)}>Nuevo registro</button>{error && <p role="alert">{error}</p>}{message && <p>{message}</p>}{editing && <form onSubmit={save}><h2>{editing === 'new' ? 'Crear registro' : 'Editar registro'}</h2>{formFields.map((field) => <label key={field}>{field.replaceAll('_', ' ')}{relationMap[field] ? <select value={form[field] ?? ''} onChange={(event) => setForm((current) => ({ ...current, [field]: event.target.value }))}><option value="">Selecciona un registro</option>{(references[field] || []).map((row) => <option key={Object.values(row)[0]} value={Object.values(row)[0]}>{optionText(row)}</option>)}</select> : <input type={field === 'password' ? 'password' : 'text'} value={form[field] ?? ''} onChange={(event) => setForm((current) => ({ ...current, [field]: event.target.value }))} />}</label>)}<button type="submit">Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form>}<div className="table-wrap"><table><thead><tr>{displayFields.map((field) => <th key={field}>{field.replaceAll('_', ' ')}</th>)}<th>Acciones</th></tr></thead><tbody>{visibleData.map((row, index) => <tr key={index}>{displayFields.map((field) => <td key={field}>{String(row[field] ?? '')}</td>)}<td><button type="button" onClick={() => openForm(row)}>Editar</button><button type="button" onClick={() => hide(row)}>Ocultar</button></td></tr>)}</tbody></table></div>{!error && !visibleData.length && <p>No hay registros para mostrar.</p>}</section>;
}
export default Modulo;
